### PR TITLE
Fix Error Handlers

### LINKED ISSUE #9: Subject lines include stack trace
This seems like a result of my recent changes.

### PR DESCRIPTION
**Pull request by sadlil**
Fixes #9

### CODE REVIEW

File: h/mail/mailer.go [hunk 1]
```diff
@@ -28,7 +28,7 @@ func (h *EmailHandler) Handle(error error) {
 		if body != "" {
 			subject := "ERROR - "
 			if err.Err() != nil {
```
Comment (TamalSaha) [inline h/mail/mailer.go]: if err.Cause() != nil

File: types.go [hunk 2]
```diff
@@ -55,6 +55,10 @@ var defaultFormatter = func(e error) string {
 			buf.WriteString("\nCaused By:\n")
 			buf.WriteString(err.cause.Error())
 		}
+		if len(err.msg) > 0 {
```
Comment (TamalSaha) [inline types.go]: It is already added on line # 53
